name: Maven CI
on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'
jobs:
  build:  
    runs-on: ubuntu-22.04
    strategy:  
      matrix:  
        java-version: [8.0.352, 11.0.23, 17.0.11, 21.0.3]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Filter Tests
        run: |
          read -r -a array <<< "$EXCLUDED_TEST_SERVICES"
          for service in "${array[@]}"; do
            for test in $(find "$services/{service}" -type d -name "test"); do
              echo "test: $test"
            done
          done
          exit 0
        env:
          EXCLUDED_TEST_SERVICES: ${{ vars.EXCLUDED_TEST_SERVICES }}
        shell: bash
      - name: Maven CI
        run: mvn -U -B clean install
